---
- name: Provision ospf1
  hosts: ospf1
  become: yes

  vars:
    neighbors:
      - 192.168.10.2
      - 192.168.30.1
    routerId: 10.0.10.0

  roles:
    - ospf-lab

- name: Provision ospf2
  hosts: ospf2
  become: yes

  vars:
    neighbors:
      - 192.168.10.1
      - 192.168.20.2
    routerId: 10.0.20.0

  roles:
    - ospf-lab

- name: Provision ospf3
  hosts: ospf3
  become: yes

  vars:
    neighbors:
      - 192.168.20.1
      - 192.168.30.2
    routerId: 10.0.30.0
  
  roles:
    - ospf-lab
